modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="regressum"
version="1.0.0"
displayName="Regressum"
authors="maksim99"
description='''
Custom logging mod for NeoForge 1.21.1.
'''

[[mixins]]
config="regressum.mixins.json"

[[dependencies.regressum]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.regressum]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"